server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_route1 #pay_route1        #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service        #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**      # 断言，路径相匹配的进行路由
        - id: pay_route2 #pay_route2        #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**     # 断言，路径相匹配的进行路由